### PR TITLE
fix: clarify OAuth page wording for non-configuring developers

### LINKED ISSUE #609: Update OAuth page wording to be more explicit about what it is
When using the MCP server with Claude Code (or other agents) along with OAuth, when a person launches Claude Code, if the credentials are expired, a page will popup with the following information

Image

This is confusing for people who have not set the MCP server themselves and might not know what this is about. This can happen if the MCP configuration is stored in git for example and it is installed for all developers of a given project.

We should update the wording to be more clear that this is related to the dbt MCP (and potentially to OAuth)

### PR DESCRIPTION
**Pull request by 4444J99**
## Summary

Updates the OAuth UI page wording to be explicit about what the page is and why it appeared:

- **Title:** "dbt Platform Setup" → "dbt MCP Server — Authentication"
- **Subtitle:** "Configure your dbt Platform connection" → explains this is OAuth for the dbt MCP server, with note: "This may have been configured by your team."
- **Error state:** "There was a problem during authentication" → "The dbt MCP server could not authenticate with dbt Cloud"
- **Completion:** "Your dbt Platform setup has finished" → "The dbt MCP server is authenticated and configured. You can close this window and return to your editor."

## Motivation

Per #609: when credentials expire, the OAuth page pops up with no context about what "dbt Platform" means. Developers who didn't configure the MCP server (e.g., it was shared via git) are confused by the generic wording.

## Addresses

Closes #609

### CODE REVIEW

**Comment by 4444J99** [comment]
Checking in — this is a small wording fix on the OAuth configuration page for developers who don't manage cloud integrations. Happy to adjust if the phrasing needs work.

File: ui/src/App.tsx [hunk 1]
```diff
@@ -517,15 +517,20 @@ export default function App() {
       </div>
       <div className="app-content">
         <header className="app-header">
-          <h1>dbt Platform Setup</h1>
-          <p>Configure your dbt Platform connection</p>
+          <h1>dbt MCP Server — Authentication</h1>
+          <p>
+            The dbt MCP server in your editor needs to authenticate with dbt
+            Cloud via OAuth. This may have been configured by your team.
```
Comment (jairus-m) [inline ui/src/App.tsx]:
```suggestion
            The dbt MCP server needs to authenticate with dbt
            Platform via OAuth. This may have been configured by your team.
```
It may not be in the case that the dbt MCP server is used in an editor. OAuth can be triggered in Claude Desktop for example. In addition, dbt Cloud --> dbt Platform.

File: ui/src/App.tsx [hunk 2]
```diff
@@ -722,8 +727,8 @@ export default function App() {
             <div className="completion-card">
               <h2>All Set!</h2>
               <p>
-                Your dbt Platform setup has finished. This window can now be
-                closed.
+                The dbt MCP server is authenticated and configured. You can
+                close this window and return to your editor.
```
Comment (jairus-m) [inline ui/src/App.tsx]:
```suggestion
                The dbt MCP server is authenticated and configured with your
                dbt Platform account. This window can now be closed.
```

Explicit with mention to dbt Platform and then same idea above with "editor".

**Comment by jairus-m** [comment]
Thank you for the contribution! Were you able to test and verify this change locally (formatting, UI works, etc.) ?

File: ui/src/App.tsx (hunk 1 above)
Comment (4444J99) [reply ui/src/App.tsx]: Applied — updated to "dbt Platform" and removed the editor-specific framing. Good call on the Claude Desktop case.

File: ui/src/App.tsx (hunk 2 above)
Comment (4444J99) [reply ui/src/App.tsx]: Done — completion message now references "dbt Platform account" explicitly.

**Comment by jairus-m** [comment]
Awesome! @4444J99 can you verify your update works locally - once that's shared, will kickoff the CI checks. In addition, pls feel free to go through the `CONTRIBUTING.md` as well. You will need to add a changelog entry.

**Comment by 4444J99** [comment]
Both suggestions applied — rebased onto latest main. Ready for re-review.

**Comment by 4444J99** [comment]
Done — changelog entry added via changie (`Under the Hood`), and caught one more "dbt Cloud" → "dbt Platform" in the error section that I'd missed.

Local build couldn't complete (Node 25 + npm dependency version mismatch on `@typescript-eslint/utils@8.57.2`), but the changes are pure string literals in JSX — here's the full diff:

**Header (line 522–523):**
```diff
- The dbt MCP server in your editor needs to authenticate with dbt
- Cloud via OAuth. This may have been configured by your team.
+ The dbt MCP server needs to authenticate with dbt
+ Platform via OAuth. This may have been configured by your team.
```

**Error message (line 532):**
```diff
- The dbt MCP server could not authenticate with dbt Cloud
+ The dbt MCP server could not authenticate with dbt Platform
```

**Completion (line 730–731):**
```diff
- The dbt MCP server is authenticated and configured. You can
- close this window and return to your editor.
+ The dbt MCP server is authenticated and configured with your
+ dbt Platform account. This window can now be closed.
```

Ready for CI.

File: ui/src/App.tsx [hunk 3]
```diff
@@ -517,15 +517,20 @@ export default function App() {
       </div>
       <div className="app-content">
         <header className="app-header">
-          <h1>dbt Platform Setup</h1>
-          <p>Configure your dbt Platform connection</p>
+          <h1>dbt MCP Server — Authentication</h1>
+          <p>
+            The dbt MCP server needs to authenticate with dbt
+            Platform via OAuth. This may have been configured by your team.
```
Comment (DevonFulcher) [inline ui/src/App.tsx]: What does: `This may have been configured by your team.` refer to? It sounds a bit ambiguous. Perhaps we leave it off or add more detail.

Comment (4444J99) [reply ui/src/App.tsx]: Good catch — that sentence was inherited from the original copy and doesn't actually refer to anything specific. Removed it in 24d2c73. The OAuth purpose is clear from context without the extra hint.
